name: ci-frontend-movies
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  # Set Node.js Version to match FE requirements (18.14)
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest
